version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - levieggertcru
  assignees:
  - levieggertcru
- package-ecosystem: swift
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - levieggertcru
  assignees:
  - levieggertcru
