matrix:
  include:
  - language: objective-c
    if: type = pull_request
    xcode_project: godtools.xcworkspace
    os: osx
    osx_image: xcode9.2
    install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - bundler install
    script:
    - fastlane gym
  - language: objective-c
    if: branch = master and type = push
    xcode_project: godtools.xcworkspace
    os: osx
    osx_image: xcode9.2
    install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - bundler install
    script:
    - fastlane ios beta
  - language: objective-c
    if: tag =~ ^v(\d+\.){1,}\d+
    xcode_project: ios/Missionhub.xcodeproj
    os: osx
    osx_image: xcode9.2
    install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - bundler install
    script:
    - fastlane ios release version:$TRAVIS_TAG submit:true auto_release:false
env:
  global:
  - secure: aV5Thx2hqXy152vQ2XmAtuz4hm6lzOyx7+cVHxp/jDMD96WSUHvfSCPnEoEcILMUDje5R5KKHpYzeTitne8suHhJ04BKjxs2wO0jmqcS5dNr5/1IwIix075+153NJStb+yYt4H1FFu1IKG0AoCPkvZ220OtQPIryd2h+eESaU/omwoZ54+dnhmy85QSt+md5OCn9yz/lqtNFjLkeDDafeu7jChSd4XwsbRWMet0H4VwnNoP7V4Qoj2+8w2zVhQbIfsFJ9jYgMCfnl+I0bNU+3HTOVc8z6qaMyoUM11h10P4luVuBdZCfow5LDaL/6gmidF3V+Kt9P3QUreTagw4v6G2bk6uL3Lf7eOpaVpQc105OrFeqlbpp34VhB3mDEekNbqh5LDFVlPh9RyP1aRwHHRqYGwBIZwP4kpIw/tj3xC1k32L3VxbK4IHQpCPoxm88fYX6uo6K0oC8cjtoEzINncKSXRN9oZknCEvh4f7iicJgr3kNFoVeIpWiTwGPyJrBzrUurohM7HsQrs+cShM1OuNvjdcj4bw/qOOFyu2Tq8jpIn8ZZLqB9jg96DmHjdMEzCCdZNg9fS3cBBW9pIZ/8X2z/1oCusjtmo/hdDLpI4d3hRKfZvcyj95gfk9zYMCDdLtWEZdKSr3zg1YREpCIiJWv9FUMCODq6ZViE5zlvBM=
  - secure: oYjULttVlWjInvUxSLbQ1MzpBGAw3mhYUxdpzW1eJfjgECucP5kdLM2M/1Mk5dfxN8sQlEZz+JLOtbnq11/1i3NiVw7FTOX4i3ACouYhbXX4YOjXobCNgFKXtN9pJQNu13Q9wEXW8z+jmxTN8/JYSA+GJqrIsLVrJuNMy/oVzv641bF+XM5RWIXXxNzVj49GUWEOskcgpyIF1G25hQN5iDN86F7xe2sgwHf+AypfWXILkEbkN4SKMqucNAM67b5GyugLXWRzEOYp9D2bF8WsJdukTbPfpJyy4NgyeyraUX1bvjx1fFt5fkHuP53P9B+3GDi3DIo/PxxwUeC8oJfdKBlCaSLLh+69VunqKXkDSs7h6J9E+HQgjXwux/VRMkE4ChqhNXNPp5QehWtRTYQnln12PDnZ/Nq++Nf/oqD07hxrKiB9djZOFX0UDhlN/RAHOu7aBCRfZxrn00hPcOByKP44GujHEqRB+NlP0kvjL4x5IKJHhRM7z9C8AviLI8YlWnsZR7SbGcvgdKcZWEOR2mK0ddmHM2c3C9LRdtu1+HtYvi+2Hawesv+kEuyroMFVgKKI2nBfz6j5x69Zw5umv/wdigKJZgTp99cFsfqw6nhaysXbJEGgkRhZJlbt3W4PmD5YLjs1RCl6it1zmnOEPx6Vxv5EQQCTi5K/vgFqKi4=
  - secure: DkAV1V6pBSwVHoc5+uSamWiXbZeVzFtouC+Em6Frvl5ShVf406idXmGuEimZFrZ32F+H0xCWBOAzd2Wr3GhN+8RRcyraVyFZeMG38srNloz+Pfi3KSbg81qz41ZRPxg0mPgI4FI3D9sySIOzt7ISFkkHiIzZ6pLZHAz89rFf1rHecTaLGtAupO7jbztCY9fAplaxF3hRon4CayGwIwUXBZpCHsyCpAcyGpwADj7f7eTuNFZC4LeMsxcYWucTEXY6a9MVLHPUbpjBI+RpgckA9A6NUX81sZOQdMg0zxH8QyTiSxADjXo0AikDVK2But6c7TYMiQSpOgVfugJUYz2ah86hr/Lb6qVdDbrQ6qxDSOdM1LpUArXmC+1OQDG3X1ShmuLgQl5JX5Fd/hV7T8NRl5bBpeWRAFILDbpcpjBasJNoGuhiFvbqRYBUoh4k+vd+f0y/dPHMAq8iZw3/dsBvxzejKM7Wrd2ZTNMO+kGQ2B3+/LbkMTUQRo55hiinCghSQQzEW0oVEvZoCzMB3/8Z6mUy/QlgJECRP+9Y41rOO4P1jMK2S4uOOwzRGlW3JNV3P/f0NpEItZ4vStaRD+NfkwWgxucctQ1Sefy1hD1UUEBxe+GQNgKdx2HXhzcvxEpnz20sfQ3DbPUeZXWu+cigfjl9eBHnFdjygT7+aEOpMUU=
  - secure: S37DNlfOchoTB3mkBkxr51bo32sjmLV5D0pa2bYejhnPjWoO5Dz5MTL3zDPwSVxGv9BVvTwgZt2vABZsyqBggYqb26PDYOQ0hu2lWT5Mhs2Xwy+7rcjZDOpN7KzR4Q1uk4pQa99dgdaqtMFw5LJQJ8+bjzZ+WXJER5AX+eM7CLzcY/uvRU7ICfCv/DjcILilZvRYMr6Ci9WTkiDuD1uBMRFHesE49uu0fnqK42D89E9/2DlTPWZ6VmtS0LOic1FTTF9L2kjDBrV6svUmVETjGrY25zfKOdMZNm8GKinWAZhu91R32z2Ujji3kjEYoYX+A3kIxXTO9TqnLuOvZM+l8NGmjpU9iu3ubFOeWStbD/cdZRUWB5tu8JWXWMAEHRzOxJ4747cJKmUXDaXfNS60tCUp2KS/BHLNCmEiHDLBWO3pKEHA3tcRdzyamzV/H2B9ExQ3QKjauQF0eBzN0d0+AGdJwXUfbyDJwgmEo9o3v/o1Ce++Y1536YkEGNjEAF17bY9xOldFI8LyQTBQN2utFGoqsJrzM0lQMJra0Ayb7xQXi78pc15wcYgqktXPbMgk0oIsrdZ7b73P0g3AFcLcgxCLZorCU2kf6eC6m6zVcPqBNwA3LYPxOZo0xTC1GUaLQ5dQHM+ACY0JNd/Eg4CbljPMLIp7929tC90t6YJlQq4=
  - secure: MRmjvQ8RyuMunoBJfwLIS6BW2wvd/CtQKRgDQoFRuD6JQNHRdu0RYV0B3jYvYaTFME47YjPfinOrb1zNeMgr491EK7/EaWfKyNU4dWzHYGQC2ldywSlSFGI394DB1BuVKF6SygX8GcgBZDCKdW2zODGw86YZb5/UfqqQK4cLhGew1s77232Gy/E5TNjPq1UHKAGx77nBKacNTD2eoQ8luejzngH+3nW/zMcbPjJ7Q025R8ygkfFCcIXLWSLXBiHuy3ZuPRg7X2lKsI6nFwOEn64fQC5aDZ2sfE2xpEf1FWkm4EGi3BDjQehF3YBYjF/0ClqT0KPJiDHwEDdyl7tRkB4EhftJyAAANLfA6i/520rYjJ7zzzDR63SeEYY+mqzryfr4m66qdlzb1lf0kGPmYwQaxKlOIstj9VPRvxfOIbaTOWjgygbyYa4HAWgdg+qMNVlpJedCPXKBYwuQo8nmpm5fsJCY/umEKKHWjuHV016qy0p3Br0jyCdMukIR+djnxkAY6n1VHrO7pQ8EWR4DrMzHWHb2q+4BwiGpb78mzkrvcWcbD/bwIF3M9FEF87eltet0JcgsfsuXiBTjguz5uB8671nxlQnHRs9wviEeXOFa8rRKpFI+0XoFqS6Dnsj+OzunR4WZHqjelc/ohQrzqIeX2cIrcieNgTiH5vX+TZI=
