language: objective-c
os: osx
osx_image: xcode10.3
xcode_project: godtools.xcworkspace
branches:
  only:
    - develop
    - master
    - /^v(\d+\.){1,}\d+/
    - /^feature\/.*$/

before_install:
  - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
  - chmod 600 ~/.netrc
install:
- gem install bundler
- bundler install

jobs:
  include:
  - name: "Build & Test GodTools"
    if: type = pull_request

    script: fastlane ios test

  - name: "Create TestFlight Build"
    if: branch = master and type = push

    script: 
    - travis_wait 45 fastlane ios beta
    - fastlane refresh_dsyms

  - name: "Release Build"
    if: tag =~ ^v(\d+\.){1,}\d+

    before_install: skip
    script: fastlane ios release auto_release:false

notifications:
  email: false
