matrix:
  include:
  - language: objective-c
    if: type = pull_request
    xcode_project: godtools.xcworkspace
    os: osx
    osx_image: xcode9.2
    install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - bundler install
    script:
    - fastlane ios test
  - language: objective-c
    if: branch = master and type = push
    xcode_project: godtools.xcworkspace
    os: osx
    osx_image: xcode9.2
    install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - chmod 600 ~/.netrc
    - bundler install
    script:
    - fastlane ios beta
  - language: node_js
    node_js:
    - '9'
    if: tag =~ ^v(\d+\.){1,}\d+
    install:
    - bundler install
    script:
    - fastlane ios release submit:true auto_release:false
