language: objective-c
os: osx
osx_image: xcode9.2
xcode_project: godtools.xcworkspace

jobs:
  include:
  - "Build & Test GodTools"
    if: type = pull_request
    install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - bundler install
    script:
    - fastlane ios test
  - "Create TestFlight Build"
    if: branch = master and type = push
    install:
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - chmod 600 ~/.netrc
    - bundler install
    script:
    - fastlane ios beta
  - "Release Build"
    if: tag =~ ^v(\d+\.){1,}\d+
    install:
    - bundler install
    script:
    - fastlane ios release auto_release:false

notifications:
  email: false
