language: swift
os: osx
osx_image: xcode12.5
xcode_project: godtools.xcworkspace
branches:
  only:
    - develop
    - master
    - /^v(\d+\.){1,}\d+/
    - /^feature\/.*$/

before_install:
  - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
  - chmod 600 ~/.netrc
install:
- gem install bundler
- bundler install

jobs:
  include:
  - name: "Build & Test GodTools"
    if: type = pull_request

    script: fastlane ios test

  - name: "Create TestFlight Build"
    if: branch = master and type = push

    before_script:
    - openssl aes-256-cbc -K $encrypted_cf3a694b4ade_key -iv $encrypted_cf3a694b4ade_iv -in fastlane/AppleAppStoreApi.json.enc -out fastlane/AppleAppStoreApi.json -d

    script:
    - fastlane ios beta
    - fastlane ios cru_build_adhoc skip_create_keychain:true
    # TODO: disabled for GT-1134
    # - fastlane refresh_dsyms

  - name: "Release Build"
    if: tag =~ ^v(\d+\.){1,}\d+

    before_install: skip
    script: fastlane ios release auto_release:false

notifications:
  email: false
