"project_id": "810418"
"api_token_env": "CROWDIN_API_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "godtools/Localizable/en.lproj/Localizable.strings",
    "translation": "godtools/Localizable/%osx_code%/%original_file_name%",
    "update_option": "update_as_unapproved"
  },
  {
    "source": "godtools/Localizable/en.lproj/Localizable.stringsdict",
    "translation": "godtools/Localizable/%osx_code%/%original_file_name%",
    "update_option": "update_as_unapproved"
  }
]