//
//  LocalizableStringKeys.swift
//  godtools
//
//  Created by Levi Eggert on 4/30/24.
//  Copyright © 2024 Cru. All rights reserved.
//

import Foundation

enum LocalizableStringKeys: String {

    case accountNavTitle = "account.navTitle"
    case accountActivityTitle = "account.activity.title"
    case accountActivitySectionTitle = "account.activity.sectionTitle"
    case accountBadgesSectionTitle = "account.badges.sectionTitle"
    case accountGlobalActivityTitle = "account.globalActivity.title"
    case accountActivityGlobalAnalyticsCountriesTitle = "accountActivity.globalAnalytics.countries.title"
    case accountActivityGlobalAnalyticsGospelPresentationTitle = "accountActivity.globalAnalytics.gospelPresentation.title"
    case accountActivityGlobalAnalyticsHeaderTitle = "accountActivity.globalAnalytics.header.title"
    case accountActivityGlobalAnalyticsLaunchesTitle = "accountActivity.globalAnalytics.launches.title"
    case accountActivityGlobalAnalyticsUsersTitle = "accountActivity.globalAnalytics.users.title"
    case accountActivityLanguagesUsed = "account.activity.languagesUsed"
    case accountActivityLessonCompletions = "account.activity.lessonCompletions"
    case accountActivityLinksShared = "account.activity.linksShared"
    case accountActivityScreenShares = "account.activity.screenShares"
    case accountActivitySessions = "account.activity.sessions"
    case accountActivityToolOpens = "account.activity.toolOpens"
    case accountJoinedOn = "account.joinedOn"
    case accountDeletedAlertTitle = "accountDeletedAlert.title"
    case accountDeletedAlertMessage = "accountDeletedAlert.message"
    case alertMailAppUnavailableTitle = "alert.mailAppUnavailable.title"
    case alertMailAppUnavailableMessage = "alert.mailAppUnavailable.message"
    case articlesRetryDownloadButtonTitle = "articles.downloadArticlesButton.title.retryDownload"
    case cancel = "cancel"
    case cardNextButtonTitle = "card_status2"
    case cardPrevButtonTitle = "card_status1"
    case close = "close"
    case confirmDeleteAccountTitle = "confirmDeleteAccount.title"
    case confirmDeleteAccountConfirmButtonTitle = "confirmDeleteAccount.confirmButton.title"
    case copyrightInfo = "copyright_info"
    case createAccount = "create_account"
    case createAccountTitle = "createAccount.title"
    case createAccountSubtitle = "createAccount.subtitle"
    case deferredDeepLinkModalTitle = "deferredDeepLinkModal.title"
    case deferredDeepLinkModalMessage = "deferredDeepLinkModal.message"
    case deleteAccountTitle = "deleteAccount.title"
    case deleteAccountSubtitle = "deleteAccount.subtitle"
    case deleteAccountConfirmButtonTitle = "deleteAccount.confirmButton.title"
    case deleteAccountCancelButtonTitle = "deleteAccount.cancelButton.title"
    case deleteAccountProgressTitle = "deleteAccountProgress.title"
    case downloadError = "download_error"
    case downloadInProgress = "Download in progress"
    case error = "error"
    case favoritesFavoriteLessonsTitle = "favorites.favoriteLessons.title"
    case favoritesFavoriteToolsTitle = "favorites.favoriteTools.title"
    case favoritesFavoriteToolsViewAll = "favorites.favoriteTools.viewAll"
    case favoritesNoToolsButton = "favorites.noTools.button"
    case favoritesNoToolsDescription = "favorites.noTools.description"
    case favoritesNoToolsTitle = "favorites.noTools.title"
    case favoritesPageTitle = "favorites.pageTitle"
    case languageSettingsNavTitle = "language_settings"
    case languageSettingsAppInterfaceTitle = "languageSettings.appInterface.title"
    case languageSettingsAppInterfaceMessage = "languageSettings.appInterface.message"
    case languageSettingsAppLanguageTitle = "languageSettings.appLanguage.title"
    case languageSettingsConfirmAppLanguageChangeLanguageButtonTitle = "languageSettings.confirmAppLanguage.changeLanguageButton.title"
    case languageSettingsConfirmAppLanguageMessage = "languageSettings.confirmAppLanguage.message"
    case languageSettingsConfirmAppLanguageNevermindButtonTitle = "languageSettings.confirmAppLanguage.nevermindButton.title"
    case languageSettingsDownloadableLanguagesTitle = "languageSettings.downloadableLanguages.title"
    case languageSettingsToolLanguagesAvailableOfflineTitle = "languageSettings.toolLanguagesAvailableOffline.title"
    case languageSettingsToolLanguagesAvailableOfflineMessage = "languageSettings.toolLanguagesAvailableOffline.message"
    case languageSettingsToolLanguagesAvailableOfflineEditDownloadedLanguagesButtonTitle = "languageSettings.toolLanguagesAvailableOffline.editDownloadedLanguagesButton.title"
    case lessonsFilterLanguageNavTitle = "lessons.filter.navBar.language"
    case lessonsFilterLessonsAvailable = "lessons.filter.lessonsAvailable"
    case loadingFavoritedTool = "loading_favorited_tool"
    case loadingUnfavoritedTool = "loading_unfavorited_tool"
    case login = "login"
    case logout = "logout"
    case menuAbout = "menu_about"
    case menuAccount = "menu_account"
    case menuAskAQuestion = "menu.askAQuestion"
    case menuDeleteAccount = "menu.deleteAccount"
    case menuGetStarted = "menu_getStarted"
    case menuLeaveAReview = "menu.leaveAReview"
    case menuLocalizationSettings = "menu.localization_settings"
    case menuReportABug = "menu.reportABug"
    case menuSendFeedback = "menu.sendFeedback"
    case menuShare = "menu_share"
    case menuSupport = "menu_support"
    case menuTutorial = "menu.tutorial"
    case menuVersion = "menu_version"
    case myTools = "my_tools"
    case networkConnectionLost = "network_connection_lost"
    case noInternet = "no_internet"
    case noInternetTitle = "no_internet_title"
    case ok = "OK"
    case openTutorialOpenTutorialButtonTitle = "openTutorial.openTutorialButton.title"
    case openTutorialShowTutorialLabelText = "openTutorial.showTutorialLabel.text"
    case privacyPolicy = "privacy_policy"
    case requiredMissingField = "required_field_missing"
    case settings = "settings"
    case shareAStoryWithUs = "share_a_story_with_us"
    case shareGodTools = "share_god_tools"
    case signInTitle = "signIn.title"
    case signInSubtitle = "signIn.subtitle"
    case signInGoogle = "signIn.google"
    case signInFacebook = "signIn.facebook"
    case signInApple = "signIn.apple"
    case startTraining = "start_training"
    case termsOfUse = "terms_of_use"
    case toolMenuItemLessons = "tool_menu_item.lessons"
    case toolMenuItemTools = "tool_menu_item.tools"
    case toolsFilterAnyCategory = "allTools.filter.anyCategory"
    case toolsFilterAnyLanguage = "allTools.filter.anyLanguage"
    case toolsFilterCategoryNavTitle = "allTools.filter.navBar.category"
    case toolsFilterLanguageNavTitle = "allTools.filter.navBar.language"
    case toolsFilterSectionTitle = "allTools.filter.title"
    case toolsFilterToolsAvailable = "tools.filter.toolsAvailable"
    case toolsSpotlightTitle = "allTools.spotlight.title"
    case toolsSpotlightSubtitle = "allTools.spotlight.description"
    case tutorialContinueButtonTitleCloseTutorial = "tutorial.continueButton.title.closeTutorial"
    case tutorialContinueButtonTitleContinue = "tutorial.continueButton.title.continue"
    case tutorialContinueButtonTitleStartUsingGodTools = "tutorial.continueButton.title.startUsingGodTools"
    case tutorialFindTutorialTitle = "tutorial.findTutorial.title"
    case tutorialLessonMessage = "tutorial.lesson.message"
    case tutorialLessonTitle = "tutorial.lesson.title"
    case tutorialScreenShareMessage = "tutorial.screenShare.message"
    case tutorialScreenShareTitle = "tutorial.screenShare.title"
    case tutorialToolMessage = "tutorial.tool.message"
    case tutorialToolTitle = "tutorial.tool.title"
    case tutorialToolTipMessage = "tutorial.toolTip.message"
    case tutorialToolTipTitle = "tutorial.toolTip.title"
}

extension LocalizableStringKeys {
    var key: String {
        return rawValue
    }
}
