name: 'Run Cocoapods Pod Install'
description: 'This action contains steps for running pod install on a project.'
inputs:
outputs:
runs:
  using: "composite"
  steps:
    - name: Checkout code
        uses: actions/checkout@v4
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4.0'
    # Required for KotlinMultiplatform
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version-file: ".java-version"
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3
    - name: Cache Cocoapods
      uses: actions/cache@v4
      with:
        path: ~/.cocoapods/repos
        key: ${{ runner.os }}-cocoapods-${{ github.sha }}
        restore-keys: ${{ runner.os }}-cocoapods-
    - name: Cache Konan
      uses: actions/cache@v4
      with:
        path: ~/.konan
        key: ${{ runner.os }}-konan-${{ github.sha }}
        restore-keys: ${{ runner.os }}-konan-
    - name: Pod install
      run: bundle exec pod install --repo-update