import_from_git(
    url: 'git@github.com:CruGlobal/cru-fastlane-files.git',
    branch: 'master',
    path: 'Fastfile'
)

platform :ios do
  desc "Run tests"
  lane :test do
    cocoapods(
        podfile: './Podfile'
    )

    run_tests(
        workspace: ENV["CRU_XCWORKSPACE"],
        scheme: ENV["CRU_TEST_SCHEME"],
        devices: ENV["CRU_TEST_DEVICES"].split(',')
    )
  end
end
