# Uncomment the lines below you want to change by removing the # in the beginning

 devices([
   "iPhone X",
   "iPhone 7",
   "iPhone 6 Plus",
   "iPhone 6",
   "iPhone 5s"
#    "iPad (5th generation)",
#    "iPad Pro (12.9-inch)"
 ])

languages([
  "en-US",
  "de-DE",
  "es-ES",
  "el",
  "fr-FR",
  "id",
  "it",
  "ms",
  "pt-BR",
  "ru",
  "th",
  "vi",
  "zh-Hant",
  "zh-Hans"
])



scheme "godtools"

workspace "godtools.xcworkspace"

clean true

clear_previous_screenshots true

stop_after_first_error true

erase_simulator true

number_of_retries 3
