
name: Run Tests, Build, and Deploy

# Controls when the workflow will run
on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: macos-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Bundle Install
        run: bundle install
        
      - name: Update Fastlane
        run: bundle update fastlane

      - name: Finished
        run: |
          echo "Finished Deploy"
