name: Download And Commit OneSky Translations

on:
  schedule:
    - cron: "0 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Bundle Install
        run: bundle install

      - name: Download And Commit Latest OneSky Localizations
        env:
          ONESKY_PUBLIC_KEY: ${{ secrets.ONESKY_PUBLIC_KEY }}
          ONESKY_SECRET_KEY: ${{ secrets.ONESKY_SECRET_KEY }}
        run: bundle exec fastlane cru_shared_lane_download_and_commit_latest_one_sky_localizations

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'latest-onesky-translations'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Latest OneSky Translations'
