name: Download And Commit OneSky Translations

on:
  schedule:
    - cron: "0 23 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cancel-previous:
      name: Cancel Stale In-progress Builds
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
          with:
            access_token: ${{ github.token }}
            
  build:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bundle Install
        run: bundle install

      - name: Download And Commit Latest OneSky Localizations
        env:
          ONESKY_PUBLIC_KEY: ${{ secrets.ONESKY_PUBLIC_KEY }}
          ONESKY_SECRET_KEY: ${{ secrets.ONESKY_SECRET_KEY }}
        run: bundle exec fastlane cru_shared_lane_download_and_commit_latest_one_sky_localizations

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'latest-onesky-translations'
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Latest OneSky Translations'