name: Download And Commit OneSky Translations

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  cancel-previous:
      name: Cancel Stale In-progress Builds
      runs-on: ubuntu-latest
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
          with:
            access_token: ${{ github.token }}
            
  build:
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Bundle Install
        run: bundle install

      - name: Download And Commit Latest OneSky Localizations
        env:
          ONESKY_PUBLIC_KEY: ${{ secrets.ONESKY_PUBLIC_KEY }}
          ONESKY_SECRET_KEY: ${{ secrets.ONESKY_SECRET_KEY }}
          GIT_BASIC_AUTHORIZATION_PAT: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION_PAT }}
        run: bundle exec fastlane cru_shared_lane_download_and_commit_latest_one_sky_localizations
