name: Update SPM Dependencies

on: 
  schedule:
    - cron: '0 6 * * 1' # Monday at 06:00 UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependencies:
    runs-on: macos-13
    env:
      FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT: 60

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2'

      # Required for KotlinMultiplatform
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: ".java-version"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Cache Cocoapods
        uses: actions/cache@v4
        with:
          path: ~/.cocoapods/repos
          key: ${{ runner.os }}-cocoapods-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cocoapods-

      - name: Cache Konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-

      - name: Pod install
        run: bundle exec pod install --repo-update

      - name: Resolve Dependencies
        id: resolution
        uses: GetSidetrack/action-xcodeproj-spm-update@main
        with:
          forceResolution: true
          failWhenOutdated: false

      - name: Create Pull Request
        if: steps.resolution.outputs.dependenciesChanged == 'true'
        uses: peter-evans/create-pull-request@v3
        with:
          branch: 'dependencies/ios'
          delete-branch: true
          commit-message: 'Update SPM Dependencies'
          title: 'Updated SPM Dependencies'